// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/thftgr/osuFastCashedBeatmapMirror",
        "contact": {
            "name": "API Support",
            "email": "thftgr@gmail.com"
        },
        "license": {
            "name": "GNU General Public License v3.0",
            "url": "https://github.com/thftgr/osuFastCashedBeatmapMirror/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/d/{map_set_id}": {
            "get": {
                "description": "비트맵셋 다운로드.",
                "summary": ".",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "download without video",
                        "name": "nv",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "download without video",
                        "name": "noVideo",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "beatmap set id",
                        "name": "map_set_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "InternalServerError",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "서버 상태 체크.",
                "summary": "Host health checker.",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "xiiov.com",
	BasePath:    "/",
	Schemes:     []string{"http", "https"},
	Title:       "Swagger Example API",
	Description: "thftgr's fast cached osu beatmap mirror.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
